name: "Packagist"

on:
  push:
    branches:
      - "master"

jobs:
  packagist-webhook:
    name: "Process Packagist Webhook"
    runs-on: ubuntu-latest
    steps:
      - name: "Send Webhook"
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://packagist.org/api/update-package?username=mnavarrocarter&apiToken=${PACKAGIST_API_TOKEN}'
          method: 'POST'
          body: '{"repository":{"url":"https://packagist.org/packages/legatus/auth"}}'